source('../../shared/libB.R')
dat=makeDataFrameML3("../../shared/ML3AllSites.csv")
f=freqEst(dat)
samp=doChain(dat)
b=bayesEst(samp)
pdf('ml3plots.pdf',width=10,height=10)
layout(matrix(c(0,1,2,0,0,5,6,0,0,3,4,0,0,7,8,0),byrow=F,ncol=2),heights=c(.2,1,1,.2,.4,1,1,.2))
par(mar=c(0,4,.5,1),cex=1.1,mgp=c(1,1,0))
plotter(subset(f,contrast=='site'),subset(b,contrast=='site'),c("Women","Men"),range=2,main="A. Suitability by Site Effects")
plotter(subset(f,contrast=='gender'),subset(b,contrast=='gender'),c("Women","Men"),range=2,main="B. Suitability by Gender")
plotter(subset(f,contrast=='credMen'),subset(b,contrast=='credMen'),c("Some","Most"),range=2,main="C. Credentialism for Men")
plotter(subset(f,contrast=='credWomen'),subset(b,contrast=='credWomen'),c("Some","Most"),range=2,main="D. Credentialism for Women")
dev.off()
